use serde::{Deserialize, Serialize};
use sqlx::FromRow;

#[derive(Debug, Serialize, Deserialize, FromRow)]
pub struct GameAdvancedStats {
    pub id: i32,
    pub game_id: i32,
    pub team_id: i32,
    pub opponent_id: i32,

    pub offense_passing_plays_explosiveness: Option<f64>,
    pub offense_passing_plays_success_rate: Option<f64>,
    pub offense_passing_plays_total_ppa: Option<f64>,
    pub offense_passing_plays_ppa: Option<f64>,
    pub offense_rushing_plays_explosiveness: Option<f64>,
    pub offense_rushing_plays_success_rate: Option<f64>,
    pub offense_rushing_plays_total_ppa: Option<f64>,
    pub offense_rushing_plays_ppa: Option<f64>,
    pub offense_passing_downs_explosiveness: Option<f64>,
    pub offense_passing_downs_success_rate: Option<f64>,
    pub offense_passing_downs_ppa: Option<f64>,
    pub offense_standard_downs_explosiveness: Option<f64>,
    pub offense_standard_downs_success_rate: Option<f64>,
    pub offense_standard_downs_ppa: Option<f64>,
    pub offense_open_field_yards_total: Option<f64>,
    pub offense_open_field_yards: Option<f64>,
    pub offense_second_level_yards_total: Option<f64>,
    pub offense_second_level_yards: Option<f64>,
    pub offense_line_yards_total: Option<f64>,
    pub offense_line_yards: Option<f64>,
    pub offense_stuff_rate: Option<f64>,
    pub offense_power_success: Option<f64>,
    pub offense_explosiveness: Option<f64>,
    pub offense_success_rate: Option<f64>,
    pub offense_total_ppa: Option<f64>,
    pub offense_ppa: Option<f64>,
    pub offense_drives: Option<i32>,
    pub offense_plays: Option<i32>,

    pub defense_passing_plays_explosiveness: Option<f64>,
    pub defense_passing_plays_success_rate: Option<f64>,
    pub defense_passing_plays_total_ppa: Option<f64>,
    pub defense_passing_plays_ppa: Option<f64>,
    pub defense_rushing_plays_explosiveness: Option<f64>,
    pub defense_rushing_plays_success_rate: Option<f64>,
    pub defense_rushing_plays_total_ppa: Option<f64>,
    pub defense_rushing_plays_ppa: Option<f64>,
    pub defense_passing_downs_explosiveness: Option<f64>,
    pub defense_passing_downs_success_rate: Option<f64>,
    pub defense_passing_downs_ppa: Option<f64>,
    pub defense_standard_downs_explosiveness: Option<f64>,
    pub defense_standard_downs_success_rate: Option<f64>,
    pub defense_standard_downs_ppa: Option<f64>,
    pub defense_open_field_yards_total: Option<f64>,
    pub defense_open_field_yards: Option<f64>,
    pub defense_second_level_yards_total: Option<f64>,
    pub defense_second_level_yards: Option<f64>,
    pub defense_line_yards_total: Option<f64>,
    pub defense_line_yards: Option<f64>,
    pub defense_stuff_rate: Option<f64>,
    pub defense_power_success: Option<f64>,
    pub defense_explosiveness: Option<f64>,
    pub defense_success_rate: Option<f64>,
    pub defense_total_ppa: Option<f64>,
    pub defense_ppa: Option<f64>,
    pub defense_drives: Option<i32>,
    pub defense_plays: Option<i32>,

    pub raw: Option<serde_json::Value>,
}
